export const GLITCH_CHARS = '!@#$%^&*<>?/\\|[]{}~RADIOACTIVE☢☣'

export const TERMINAL_LINES = [
  '> SYSTEM BOOT... OK',
  '> RADIATION LEVELS: CRITICAL',
  '> LOADING PERSONNEL FILE...',
  '> CLEARANCE LEVEL: MAXIMUM',
  '> FILE DECRYPTED. DISPLAYING...',
]
