export const PARTICLE_COUNT_DESKTOP = 90
export const PARTICLE_COUNT_LOW_POWER = 44
export const PARTICLE_COUNT_MOBILE = 22
export const DESKTOP_TARGET_FPS = 28
export const MOBILE_TARGET_FPS = 20
export const SNOW_STARTUP_DELAY_MS = 1800
